### ISSUE TITLE
Error: paramter 'project' should be a file or directory.

### ISSUE THREAD

**Issue by lfrallon** [alexcanessa/typescript-coverage-report#119]
``` 
$ typescript-coverage-report
Error: paramter 'project' should be a file or directory.
    at getTsConfigFilePath (/home/user/Documents/myproject/node_modules/type-coverage-core/dist/tsconfig.js:87:15)
    at getTsConfig (/home/user/Documents/myproject/node_modules/type-coverage-core/dist/tsconfig.js:125:62)
    at async getProjectRootNamesAndCompilerOptions (/home/user/Documents/myproject/node_modules/type-coverage-core/dist/tsconfig.js:14:20)
    at async lint (/home/user/Documents/myproject/node_modules/type-coverage-core/dist/core.js:17:44)
```

**Environment Setup**

Tool Version: 0.7.0
OS: Linux (Fedora 37)
 NodeJs Version: v18.12.1

**Comment by lfrallon** [comment]
It's my bad. Found out that I extended my `tsconfig.json` with `"extends": "@tsconfig/react-native/tsconfig.json",`  but haven't installed it as my dev dependencies. :)

Fix the issue by:
```
yarn add --dev @tsconfig/react-native

```
