### ISSUE TITLE
Bug: Table defaultProp warning in output

### ISSUE THREAD

**Issue by SarfDime** [alexcanessa/typescript-coverage-report#170]
**Describe the bug**
- A warning shows in the output

**To Reproduce**
- Run the default command  `npx typescript-coverage-report`

**Expected behaviour**
- No warnings

**Screenshots**
- 
![Screenshot from 2024-12-11 15-55-06](https://github.com/user-attachments/assets/cc381e00-48e3-42ca-a17f-f6ace9db91d5)

**Environment**
 - Tool version: latest
 - OS: any
 - Node version: v20.12.2 (npm v10.5.0)]

**Additional context**
### Full warning
`Warning: Table: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
- at Table (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/collections/Table/Table.js:38:24)
- at div
- at Container (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/elements/Container/Container.js:22:24)
- at SummaryPage (/opt/build/repo/node_modules/typescript-coverage-report/dist/components/SummaryPage/SummaryPage.js:11:25)

Warning: TableHeader: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
- at TableHeader (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/collections/Table/TableHeader.js:22:24)
- at table
- at Table (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/collections/Table/Table.js:38:24)
- at div
- at Container (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/elements/Container/Container.js:22:24)
- at SummaryPage (/opt/build/repo/node_modules/typescript-coverage-report/dist/components/SummaryPage/SummaryPage.js:11:25)

Warning: TableRow: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
- at TableRow (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/collections/Table/TableRow.js:28:22)
- at thead
- at TableHeader (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/collections/Table/TableHeader.js:22:24)
- at table
- at Table (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/collections/Table/Table.js:38:24)
- at div
- at Container (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/elements/Container/Container.js:22:24)
- at SummaryPage (/opt/build/repo/node_modules/typescript-coverage-report/dist/components/SummaryPage/SummaryPage.js:11:25)

Warning: TableHeaderCell: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
- at TableHeaderCell (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/collections/Table/TableHeaderCell.js:24:18)
- at tr
- at TableRow (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/collections/Table/TableRow.js:28:22)
- at thead
- at TableHeader (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/collections/Table/TableHeader.js:22:24)
- at table
- at Table (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/collections/Table/Table.js:38:24)
- at div
- at Container (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/elements/Container/Container.js:22:24)
- at SummaryPage (/opt/build/repo/node_modules/typescript-coverage-report/dist/components/SummaryPage/SummaryPage.js:11:25)

Warning: TableCell: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
- at TableCell (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/collections/Table/TableCell.js:26:22)
- at TableHeaderCell (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/collections/Table/TableHeaderCell.js:24:18)
- at tr
- at TableRow (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/collections/Table/TableRow.js:28:22)
- at thead
- at TableHeader (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/collections/Table/TableHeader.js:22:24)
- at table
- at Table (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/collections/Table/Table.js:38:24)
- at div
- at Container (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/elements/Container/Container.js:22:24)
- at SummaryPage (/opt/build/repo/node_modules/typescript-coverage-report/dist/components/SummaryPage/SummaryPage.js:11:25)

Warning: TableBody: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
- at TableBody (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/collections/Table/TableBody.js:19:24)
- at table
- at Table (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/collections/Table/Table.js:38:24)
- at div
- at Container (/opt/build/repo/node_modules/semantic-ui-react/dist/commonjs/elements/Container/Container.js:22:24)
- at SummaryPage (/opt/build/repo/node_modules/typescript-coverage-report/dist/components/SummaryPage/SummaryPage.js:11:25)`

**Comment by aderiushev** [comment]
up, same here

**Comment by CentillionJinx** [comment]
Still undone?
