### ISSUE TITLE
Bug: I can't run de coverage

### ISSUE THREAD

**Issue by lflimeira** [alexcanessa/typescript-coverage-report#50]
**Describe the bug**
When I run the command I get the following error:

```
TypeError: typescript_1.default.isNamedTupleMember is not a function
    at checkNode (/Users/lflimeira/Projects/z1/api/node_modules/typescript-coverage-report/node_modules/type-coverage-core/dist/checker.js:598:30)
    at Object.checkNode (/Users/lflimeira/Projects/z1/api/node_modules/typescript-coverage-report/node_modules/type-coverage-core/dist/checker.js:521:9)
    at /Users/lflimeira/Projects/z1/api/node_modules/typescript-coverage-report/node_modules/type-coverage-core/dist/core.js:96:23
    at visitNodes (/Users/lflimeira/Projects/z1/api/node_modules/typescript-coverage-report/node_modules/typescript/lib/typescript.js:18956:30)
    at Object.forEachChild (/Users/lflimeira/Projects/z1/api/node_modules/typescript-coverage-report/node_modules/typescript/lib/typescript.js:19189:24)
    at SourceFileObject.NodeObject.forEachChild (/Users/lflimeira/Projects/z1/api/node_modules/typescript-coverage-report/node_modules/typescript/lib/typescript.js:138333:23)
    at Object.lint (/Users/lflimeira/Projects/z1/api/node_modules/typescript-coverage-report/node_modules/type-coverage-core/dist/core.js:95:20)
```

**To Reproduce**
I just followed the `typescript-coverage-report` documentation about how to install and run de coverage.

**Expected behavior**
to run the `typescript-coverage-report` properly. 

**Environment**
 - Tool version: 0.4.0 
 - OS: MacOS Catalina
 - Node version: v14.6.0

**Comment by alexcanessa** [comment]
@lflimeira what TS version are you on?

**Comment by lflimeira** [comment]
@alexcanessa the TS version that I'm using is 4.1.3.

**Comment by alexcanessa** [comment]
@lflimeira we're going to support `4` very soon. I'll keep you posted here and you can try again!

**Comment by alexcanessa** [comment]
@lflimeira `0.5.0` is now out. Check again and let me know.

**Comment by lflimeira** [comment]
@alexcanessa thank you for your attention. I will test again and will let you know if something shows up. 😄

**Comment by alexcanessa** [comment]
@lflimeira could you let me know if the issue was fixed? I'd like to close it if it is.
